name: test_torrent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dtorrent_parser: ^1.0.8
  dtorrent_task: ^0.3.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  path: ^1.9.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  meta: 1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/